---
functional:
  - Пользователь сайта должен иметь возможность зарегистрироваться на сайте
  - Пользователь сайта должен иметь возможность авторизироваться на сайте
  - Возможность сохранить прогресс игры в личном кабинете пользователя
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
implicit:
  - Возможность неавторирзированным пользователям выбор игры с ботом или с пользователем
  - Возможность переключения на русский язык пользования
  - Уведомление пользователя об успешной регистрации на сайте
  - Сайт должен иметь возможность создания надежного пароля c помощью символов
  - Инерфейс  должен быть удобен для пользователя
