---
functional:
  - Пользователь сайта должен иметь возможность зарегистрироваться на сайте
  - Пользователь сайта должен иметь возможность авторизироваться на сайте
  - Возможность сохранить прогресс игры в личном кабинете пользователя
  - Сайт должен быть доступен неавторизированным пользователям
  - Пользователь может выбирать задачи по уровню сложности
  - Пользователь может решать задачи на любом языке программирования
  - Пользователь может задать время при запуске игры
  - Сайт должен отображать таблицу с рейтингом пользователей
  - Возможность пользователя создавать новую задачу
  - Возможность создания турнира между пользователями
  - Пользователь может отправлять сообщения в чат другому пользователю во время игры
  - Во время запуска игры должен отбражаться таймер
  - По окончанию игры должно появиться оповещение об исходе игры
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
implicit:
  - Возможность неавторизованным пользователям выбирать игру как с ботом, так и с человеком
  - Сайт должен быть доступен на разных языках
  - Уведомление пользователя об успешной регистрации на сайте
  - При создании пользователя должна быть возможность указывать в пароле более чем один символ, который не является буквой или цифрой
